# Installs the git hooks for this repository.
#
# WHY A SHIM AND NOT A STRAIGHT COPY
#
# The documented instruction used to be "Copy-Item scripts\pre-commit.ps1
# .git\hooks\pre-commit". That does not work. Git invokes hooks through its own shell,
# which will not run a file that has PowerShell content but no .ps1 extension:
#
#   Processing -File '.git/hooks/pre-commit' failed because the file does not have
#   a '.ps1' extension.
#
# Every commit then fails for a reason that has nothing to do with the code, so the
# realistic outcome is that the hook gets deleted and nothing is enforced at all. This
# installer writes a small sh shim per hook that forwards to the real PowerShell script,
# and stdin is inherited so the pre-push hook still receives its ref lines.
#
# ASCII only - see scripts/check-test-filters.ps1 for why.

[CmdletBinding()]
param(
    # Overwrite hooks that already exist.
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot

$hooksDir = Join-Path (git rev-parse --git-path hooks).Trim() ''
if (-not (Test-Path $hooksDir)) {
    New-Item -ItemType Directory -Force -Path $hooksDir | Out-Null
}

$hooks = @(
    @{ Name = 'pre-commit'; Script = 'scripts/pre-commit.ps1' }
    @{ Name = 'pre-push';   Script = 'scripts/pre-push.ps1' }
)

foreach ($hook in $hooks) {
    $target = Join-Path $hooksDir $hook.Name

    if ((Test-Path $target) -and -not $Force) {
        Write-Host "SKIP $($hook.Name) - already installed (use -Force to overwrite)" -ForegroundColor Yellow
        continue
    }

    # LF endings and no BOM: sh will not run a script with CRLF or a BOM.
    $shim = @(
        '#!/bin/sh',
        '# Generated by scripts/install-hooks.ps1 - do not edit.',
        "exec powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"`$(git rev-parse --show-toplevel)/$($hook.Script)`""
    ) -join "`n"

    [System.IO.File]::WriteAllText($target, $shim + "`n", (New-Object System.Text.UTF8Encoding($false)))
    Write-Host "OK   $($hook.Name) -> $($hook.Script)" -ForegroundColor Green
}

Write-Host ""
Write-Host "Hooks installed in $hooksDir"
Write-Host ""
Write-Host "  pre-commit : static gates, COM leak check, smoke tests"
Write-Host "  pre-push   : refuses to push src/ or tests/ changes without integration"
Write-Host "               evidence for the pushed commit (scripts/Invoke-LocalIntegrationGate.ps1)"
